name: "TF Plan & Lint"
on:
  pull_request:
    branches: [main]
    paths:
      - "terraform/environments/**"
      - "terraform/modules/**"
permissions:
  id-token: write
  contents: read

jobs:
  plan:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_USE_OIDC: true
    steps:
      - uses: actions/checkout@v4
      - uses: terraform-linters/setup-tflint@v4

      - name: Run TFLint
        run: |
          tflint --init
          tflint
        working-directory: ./terraform/environments/main

      - uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform init -input=false -backend-config=backend.github.test.hcl
        working-directory: ./terraform/environments/main

      - name: Terraform Plan
        run: terraform plan -input=false
        working-directory: ./terraform/environments/main
