name: "PR 1: TF Static Checks"
on:
  push:
    paths:
      - "terraform/**"
    paths-ignore:
      - "terraform/bootstrap/**"

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Format
        run: terraform fmt -check -recursive terraform/environments terraform/modules

      - name: Terraform Init
        run: terraform init -backend=false
        working-directory: ./terraform/environments/main

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./terraform/environments/main

      - name: Security Scan (tfsec)
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          working_directory: ./terraform/environments/main
