name: "PR 1: TF Static Checks"
on:
  push:
    paths:
      - "terraform/environments/**"
      - "terraform/modules/**"
permissions:
  id-token: write
  contents: read
jobs:
  static-analysis:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_USE_OIDC: true
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Format
        run: terraform fmt -check -recursive terraform/environments terraform/modules

      - name: Terraform Init
        run: terraform init -input=false -backend-config=backend.github.hcl
        working-directory: ./terraform/environments/main

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./terraform/environments/main

      - name: Security Scan (tfsec)
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          working_directory: ./terraform/environments/main
